// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb8jxksjDKgxB4IFmMLxxXWAReLclS7Ko',
    appId: '1:18586642629:web:9ceeefbd89c38f7cfca8ac',
    messagingSenderId: '18586642629',
    projectId: 'mango-production-95be3',
    authDomain: 'mango-production-95be3.firebaseapp.com',
    storageBucket: 'mango-production-95be3.firebasestorage.app',
    measurementId: 'G-QX3KSG81DW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeAHudI1cCUbPUPPs3joPaUkwLE8JCoT0',
    appId: '1:18586642629:android:5d57fdeae26c2492fca8ac',
    messagingSenderId: '18586642629',
    projectId: 'mango-production-95be3',
    storageBucket: 'mango-production-95be3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIgPu65BwcIpKP1ntualSP03g4zn-dNSg',
    appId: '1:18586642629:ios:a72fc1c7cc66d6fcfca8ac',
    messagingSenderId: '18586642629',
    projectId: 'mango-production-95be3',
    storageBucket: 'mango-production-95be3.firebasestorage.app',
    iosBundleId: 'com.example.mango',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIgPu65BwcIpKP1ntualSP03g4zn-dNSg',
    appId: '1:18586642629:ios:a72fc1c7cc66d6fcfca8ac',
    messagingSenderId: '18586642629',
    projectId: 'mango-production-95be3',
    storageBucket: 'mango-production-95be3.firebasestorage.app',
    iosBundleId: 'com.example.mango',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDb8jxksjDKgxB4IFmMLxxXWAReLclS7Ko',
    appId: '1:18586642629:web:3a45a14647ef8fb8fca8ac',
    messagingSenderId: '18586642629',
    projectId: 'mango-production-95be3',
    authDomain: 'mango-production-95be3.firebaseapp.com',
    storageBucket: 'mango-production-95be3.firebasestorage.app',
    measurementId: 'G-HC43X8HN6J',
  );
}
