// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx9Mv1i6SwMYBoGpjwO84oxs-7rwz6ubM',
    appId: '1:194825118119:web:fc6250057c4003e45e9682',
    messagingSenderId: '194825118119',
    projectId: 'mango-e0232',
    authDomain: 'mango-e0232.firebaseapp.com',
    storageBucket: 'mango-e0232.firebasestorage.app',
    measurementId: 'G-8HD50TKZ28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABzocnnQEPNS-_iHkPlaoHBaaRNdP4Kfg',
    appId: '1:194825118119:android:7d81786ca2d16f6a5e9682',
    messagingSenderId: '194825118119',
    projectId: 'mango-e0232',
    storageBucket: 'mango-e0232.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF5OvyJZByN8fwQAwFahxrEBruNZiiBWo',
    appId: '1:194825118119:ios:6dbe63734d7d793b5e9682',
    messagingSenderId: '194825118119',
    projectId: 'mango-e0232',
    storageBucket: 'mango-e0232.firebasestorage.app',
    iosBundleId: 'com.example.mango',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF5OvyJZByN8fwQAwFahxrEBruNZiiBWo',
    appId: '1:194825118119:ios:6dbe63734d7d793b5e9682',
    messagingSenderId: '194825118119',
    projectId: 'mango-e0232',
    storageBucket: 'mango-e0232.firebasestorage.app',
    iosBundleId: 'com.example.mango',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx9Mv1i6SwMYBoGpjwO84oxs-7rwz6ubM',
    appId: '1:194825118119:web:1f728cc5757f82c15e9682',
    messagingSenderId: '194825118119',
    projectId: 'mango-e0232',
    authDomain: 'mango-e0232.firebaseapp.com',
    storageBucket: 'mango-e0232.firebasestorage.app',
    measurementId: 'G-NXD3YSQZDK',
  );
}
